"""
FairExplain AI — Explanation Report Model
===========================================
Maps to the `explanation_reports` table per DATA_MODEL.md §3.8.

Generated by the LLM Explanation Layer (Phase 5).
"""

from __future__ import annotations

import enum
import uuid

from sqlalchemy import ARRAY, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class AssessmentType(str, enum.Enum):
    scholarship = "scholarship"
    loan = "loan"


class ExplanationReport(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """
    LLM-generated explanation + fairness note tied to a single assessment.

    `assessment_id` is a bare UUID referencing either `ScholarshipAssessment`
    or `LoanAssessment` depending on `assessment_type`.  Using a polymorphic
    FK avoids a join-table while keeping the schema simple.
    """

    __tablename__ = "explanation_reports"

    assessment_type: Mapped[AssessmentType] = mapped_column(
        String(20), nullable=False, index=True
    )
    assessment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK to ScholarshipAssessment or LoanAssessment depending on assessment_type",
    )
    recommendation_text: Mapped[str] = mapped_column(Text, nullable=False)
    reasons: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    confidence_note: Mapped[str] = mapped_column(Text, nullable=False)
    fairness_note: Mapped[str] = mapped_column(
        Text, nullable=False, comment="Result of Fairness Checker pass"
    )
    llm_prompt_version: Mapped[str] = mapped_column(
        String(50), nullable=False, comment="For reproducibility/audit"
    )

    def __repr__(self) -> str:
        return (
            f"<ExplanationReport id={self.id} "
            f"type={self.assessment_type} assessment_id={self.assessment_id}>"
        )
